//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beepoy.Web.Models
{
    using System;
    using System.Data.Entity;
    
    public partial class MvcBeepoyEntities : DbContext
    {
        public MvcBeepoyEntities()
            : base("name=MvcBeepoyEntities")
        {
        }
    
        public DbSet<Beep> Beeps { get; set; }
        public DbSet<BeepsTag> BeepsTags { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventsTag> EventsTags { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TrackUserEvent> TrackUserEvents { get; set; }
        public DbSet<TrackUserPlace> TrackUserPlaces { get; set; }
        public DbSet<TrackUserUser> TrackUserUsers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<BeepsEvent> BeepsEvents { get; set; }
        public DbSet<BeepsPlace> BeepsPlaces { get; set; }
        public DbSet<BeepsUser> BeepsUsers { get; set; }
    }
}
