//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beepoy.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventsTags = new HashSet<EventsTag>();
            this.TrackUserEvents = new HashSet<TrackUserEvent>();
            this.BeepsEvents = new HashSet<BeepsEvent>();
        }
    
        // Primitive properties
    
        public long EventId { get; set; }
        public long PlaceId { get; set; }
        public long UserId { get; set; }
        public System.DateTime DateInsert { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string IdName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ImageUrl { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<EventsTag> EventsTags { get; set; }
        public virtual ICollection<TrackUserEvent> TrackUserEvents { get; set; }
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BeepsEvent> BeepsEvents { get; set; }
    
    }
}
