//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beepoy.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Beeps = new HashSet<Beep>();
            this.Events = new HashSet<Event>();
            this.Places = new HashSet<Place>();
            this.TrackUserEvents = new HashSet<TrackUserEvent>();
            this.TrackUserPlaces = new HashSet<TrackUserPlace>();
            this.TrackUserUsers = new HashSet<TrackUserUser>();
            this.TrackUserUsersTracked = new HashSet<TrackUserUser>();
        }
    
        // Primitive properties
    
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime DateInsert { get; set; }
        public System.DateTime DateUpdate { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Beep> Beeps { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<TrackUserEvent> TrackUserEvents { get; set; }
        public virtual ICollection<TrackUserPlace> TrackUserPlaces { get; set; }
        public virtual ICollection<TrackUserUser> TrackUserUsers { get; set; }
        public virtual ICollection<TrackUserUser> TrackUserUsersTracked { get; set; }
    
    }
}
